rows: 6
blacklist:
  - netherite
  - copper
  - diamond
  - emerald
  - iron
  - leather
  - book
  - potion
  - sword
  - redstone
  - axe
  - shovel
  - hoe
  - elytra
  - trident
  - mace
  - fishing_rod
  - lapis
  - gold
  - bow
  - shield
  - ore
  - totem
  - trim
  - chorus_fruit
  - beacon
  - nether_star
  - blaze
  - brewing_stand
  - ender
  - ancient_debris
  - enchanting_table
  - ore
  - ominous_bottle
  - snowball
  - breeze_rod